import { createServer } from 'node:http'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { spawn, type ChildProcess } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const frontendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const repoDir = path.resolve(frontendDir, '..')
const python = process.env.VESPER_E2E_PYTHON ?? process.env.PYTHON ?? 'python3'
type ManagedChild = { process: ChildProcess; output: () => string }
export type Harness = { backend: ManagedChild; frontend: ManagedChild; home: string; backendUrl: string; frontendUrl: string; restart: () => Promise<void>; close: () => Promise<void> }
export type HarnessOptions = { firstBootCompleted?: boolean }

async function freePort(): Promise<number> { return await new Promise((resolve, reject) => { const server = createServer(); server.once('error', reject); server.listen(0, '127.0.0.1', () => { const address = server.address(); server.close(error => error ? reject(error) : resolve((address as { port: number }).port)) }) }) }
async function waitFor(url: string): Promise<void> { const deadline = Date.now() + 15_000; let lastError: unknown; while (Date.now() < deadline) { try { const response = await fetch(url); if (response.ok) return; lastError = new Error(`${url}: ${response.status}`) } catch (error) { lastError = error } await new Promise(resolve => setTimeout(resolve, 100)) } throw lastError ?? new Error(`Timed out waiting for ${url}`) }
function child(command: string, args: string[], cwd: string, env: NodeJS.ProcessEnv): ManagedChild { const process = spawn(command, args, { cwd, env, stdio: ['ignore', 'pipe', 'pipe'] }); let output = ''; process.on('error', error => { output += `${error.name}: ${error.message}\n` }); process.stdout?.on('data', chunk => { output += String(chunk) }); process.stderr?.on('data', chunk => { output += String(chunk) }); return { process, output: () => output } }
async function stop(child: ManagedChild): Promise<void> { const process = child.process; if (process.exitCode !== null || process.killed) return; process.kill('SIGTERM'); await Promise.race([new Promise<void>(resolve => process.once('exit', () => resolve())), new Promise<void>(resolve => setTimeout(resolve, 5_000))]); if (process.exitCode === null) process.kill('SIGKILL') }
export async function startHarness(options: HarnessOptions = {}): Promise<Harness> { const home = await mkdtemp(path.join(tmpdir(), 'vesper-gate-f-')); const backendPort = await freePort(); const frontendPort = await freePort(); const backendEnv = { ...process.env, VESPER_HOME: home, PYTHONUNBUFFERED: '1' }; const firstBootSetting = options.firstBootCompleted === false ? '' : "runtime.core_apps.update_settings({'first_boot_completed': True}, 'gate-f-onboarding-fixture')"; const backendProgram = ['from pathlib import Path', 'from vesper.api import Runtime, create_app', 'from vesper.syscalls import Decision', 'import uvicorn', `runtime = Runtime(Path(${JSON.stringify(home)}))`, 'runtime.start()', "runtime.syscalls.grant(operation='test.effect', resource_selector='e2e-denied-target', decision=Decision.DENY, issuer='director', rule_id='e2e-canonical-deny')", "runtime.syscalls.grant(operation='test.effect', resource_selector='e2e-anchor-protected-target', decision=Decision.DENY, issuer='director', rule_id='e2e-anchor-authority-deny')", 'app = create_app(runtime)', firstBootSetting, `uvicorn.run(app, host='127.0.0.1', port=${backendPort})`].filter(Boolean).join('\n'); let backend = child(python, ['-c', backendProgram], repoDir, backendEnv); const frontendEnv = { ...backendEnv, VESPER_API_TARGET: `http://127.0.0.1:${backendPort}` }; let frontend = child('npm', ['run', 'dev', '--', '--host', '127.0.0.1', '--port', String(frontendPort), '--strictPort'], frontendDir, frontendEnv); const backendUrl = `http://127.0.0.1:${backendPort}`; const frontendUrl = `http://127.0.0.1:${frontendPort}`; try { await Promise.all([waitFor(`${backendUrl}/health`), waitFor(frontendUrl)]) } catch (error) { const diagnostic = `backend:\n${backend.output()}\nfrontend:\n${frontend.output()}`; await stop(backend); await stop(frontend); await rm(home, { recursive: true, force: true }); throw new Error(`${String(error)}\n${diagnostic}`) } const restart = async () => { await stop(frontend); await stop(backend); backend = child(python, ['-c', backendProgram], repoDir, backendEnv); frontend = child('npm', ['run', 'dev', '--', '--host', '127.0.0.1', '--port', String(frontendPort), '--strictPort'], frontendDir, frontendEnv); await Promise.all([waitFor(`${backendUrl}/health`), waitFor(frontendUrl)]) }; return { get backend() { return backend }, get frontend() { return frontend }, home, backendUrl, frontendUrl, restart, close: async () => { await stop(frontend); await stop(backend); await rm(home, { recursive: true, force: true }) } } }
export async function bootstrap(baseUrl: string): Promise<string> { const response = await fetch(`${baseUrl}/api/bootstrap`); if (!response.ok) throw new Error(`bootstrap failed: ${response.status}`); return (await response.json()).session }
export async function command(baseUrl: string, token: string, url: string, body: unknown): Promise<Response> { return fetch(`${baseUrl}${url}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Vesper-Bootstrap': token, 'X-Client-Request-ID': crypto.randomUUID() }, body: JSON.stringify(body) }) }
