import { expect, test } from '@playwright/test'
import { startHarness } from './support/vesper-harness'

test('E-01 repeated Director workflow survives runtime restart and a second cycle', async ({ browser }) => {
  const h = await startHarness()
  try {
    const first = await browser.newPage()
    await first.goto(h.frontendUrl)
    await expect(first.getByText('VESPER')).toBeVisible()
    await expect(first.getByRole('heading', { name: /Attention|Good work starts here/ })).toBeVisible()

    await first.getByLabel('Ask Vesper').fill('first daily briefing cycle')
    await first.getByLabel('Ask Vesper').press('Enter')
    await expect(first.getByRole('alert')).toContainText('AI connection is not configured')
    await first.getByRole('button', { name: 'Projects' }).click()
    await first.getByPlaceholder('New project name').fill('E01 Project One')
    await first.getByRole('button', { name: '+ Create' }).click()
    await expect(first.getByText('Project committed')).toBeVisible()
    await first.getByRole('button', { name: 'Tasks' }).click()
    await first.getByPlaceholder('Add a task').fill('E01 Task One')
    await first.getByRole('button', { name: '+ Create' }).click()
    await expect(first.getByText('Task committed')).toBeVisible()
    await first.getByRole('button', { name: 'Calendar' }).click()
    await first.getByPlaceholder('Event title').fill('E01 Event One')
    await first.getByRole('button', { name: '+ Add event' }).click()
    await expect(first.getByText('Calendar item committed')).toBeVisible()
    await first.getByRole('button', { name: 'Ideas' }).click()
    await first.getByPlaceholder('What are you noticing?').fill('E01 idea one')
    await first.getByRole('button', { name: 'Capture idea' }).click()
    await expect(first.getByText('Idea persisted')).toBeVisible()
    for (const name of ['Processes', 'Observability', 'Memory', 'Approvals', 'Connections', 'Settings']) {
      await first.getByRole('button', { name }).click()
      await expect(first.locator('h2')).toContainText(name)
    }
    await first.getByRole('button', { name: 'Settings', exact: true }).click()
    await first.getByLabel('Director display name').fill('E01 Director')
    await first.getByRole('button', { name: 'Save settings' }).click()
    await expect(first.getByText('Settings committed')).toBeVisible()
    await first.close()

    await h.restart()
    const second = await browser.newPage()
    await second.goto(h.frontendUrl)
    await expect(second.getByText('VESPER')).toBeVisible()
    await second.getByRole('button', { name: 'Projects' }).click()
    await expect(second.getByText('E01 Project One')).toBeVisible()
    await second.getByRole('button', { name: 'Tasks' }).click()
    await expect(second.getByText('E01 Task One')).toBeVisible()
    await second.getByRole('button', { name: 'Calendar' }).click()
    await expect(second.getByText(/E01 Event One/)).toBeVisible()
    await second.getByRole('button', { name: 'Ideas' }).click()
    await expect(second.getByText('E01 idea one')).toBeVisible()
    await second.getByRole('button', { name: 'Settings' }).click()
    await expect(second.getByLabel('Director display name')).toHaveValue('E01 Director')

    await second.getByLabel('Ask Vesper').fill('second daily briefing cycle')
    await second.getByLabel('Ask Vesper').press('Enter')
    await expect(second.getByRole('alert')).toContainText('AI connection is not configured')
    await second.getByRole('button', { name: 'Projects' }).click()
    await second.getByPlaceholder('New project name').fill('E01 Project Two')
    await second.getByRole('button', { name: '+ Create' }).click()
    await expect(second.getByText('Project committed')).toBeVisible()
    await second.getByRole('button', { name: 'Tasks' }).click()
    await second.getByPlaceholder('Add a task').fill('E01 Task Two')
    await second.getByRole('button', { name: '+ Create' }).click()
    await expect(second.getByText('Task committed')).toBeVisible()
    await second.getByRole('button', { name: 'Ideas' }).click()
    await second.getByPlaceholder('What are you noticing?').fill('E01 idea two')
    await second.getByRole('button', { name: 'Capture idea' }).click()
    await expect(second.getByText('Idea persisted')).toBeVisible()
    await second.getByRole('button', { name: 'Processes' }).click()
    await expect(second.locator('h2')).toContainText('Processes')
    await second.getByRole('button', { name: 'Observability' }).click()
    await expect(second.locator('h2')).toContainText('Observability')
    await second.close()
  } finally {
    await h.close()
  }
})